version: '3.8'

services:
  # Apenas o banco de dados PostgreSQL
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: pdtic_db
      POSTGRES_USER: pdtic_user
      POSTGRES_PASSWORD: pdtic_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: