# Generated by Django 5.1.5 on 2025-09-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('elaboracao', 'Em Elaboração'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='instituicoes.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoPDTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versao', models.CharField(max_length=20)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='pdtic_docs/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pdtic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='pdtic.pdtic')),
            ],
        ),
    ]
