# Generated by Django 5.2.7 on 2025-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='cor_tema',
            field=models.CharField(default='#3B82F6', help_text='Cor tema da instituição em formato hexadecimal (ex: #3B82F6)', max_length=7),
        ),
    ]
